---
appName:
  - "biocollect"
layout:
  skin: "ala2"

environments:
    development:
        grails:
           config:
              locations:
                 - file:///data/biocollect/config/biocollect-config-grails3.properties
           # It is used by redirect and others
           serverURL: "${server.serverURL}"
        bugherd:
           integration : false
        server:
           port: 8087
           serverURL: http://devt.ala.org.au:8087
        security:
          cas:
             appServerName: 'http://devt.ala.org.au:8087'
    test:
        grails:
          config:
             locations:
                - file:///data/biocollect/config/biocollect-config.properties
        server:
             serverURL: https://biocollect-test.ala.org.au
        security:
           cas:
               appServerName: https://biocollect-test.ala.org.au
    production:
        grails:
         config:
             locations:
                - file:///data/biocollect/config/biocollect-config.properties
         serverURL: "http://www.ala.org.au/biocollect"


grails:
    project:
      groupId: "au.org.ala"
    profile: web
    codegen:
        defaultPackage: au.org.ala.biocollect
    cache:
       defaults:
          eternal: true
          overflowToDisk: false
          maxElementsInMemory: 20000
          timeToLiveSeconds: 3600
          name: 'vocabListCache'
       ehcache:
            cacheManagerName : "${appName}-ehcache"
            reloadable : false
    mime:
        file:
          extensions: true
        use:
          accept:
            header: true
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: none
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: none  #${ } will be html encoded if set to default to html
                scriptlets: html
                taglib: none
                staticparts: none
            sitemesh:
              preprocess: true

    resources:
      resourceLocatorEnabled: true
      adhoc:
          patterns: ['/images/*', '/css/*', '/js/*', '/plugins/*', '/vendor/*']
          includes: ['/images/**', '/css/**', '/js/**', '/plugins/**', '/vendor/**']

    scaffolding:
      templates:
        domainSuffix: 'Instance'
    json:
      legacy:
        builder: false
    # enabled native2ascii conversion of i18n properties files
    enable:
      native2ascii: true
    # packages to include in Spring bean scanning
    spring:
      bean:
        packages: []
    # whether to disable processing of multi part requests
    web:
      disable:
        multipart: false

    # request parameters to mask when logging exceptions
    exceptionresolver:
      params:
        exclude: ['password']


app:
  default:
    hub: "ala"
  view:
    nocache: false
  http:
    header:
      userId: "X-ALA-userId"


security:
   cas:
      casProperties: "casServerLoginUrl,serverName,centralServer,casServerName,uriFilterPattern,uriExclusionFilter,authenticateOnlyIfLoggedInFilterPattern,casServerLoginUrlPrefix,gateway,casServerUrlPrefix,contextPath,gatewayStorageClass"
      uriExclusionFilterPattern: "/assets/.*,/images.*,/css.*,/js.*,/less.*,/ajax/bulkLookupQuestions,/uploads/.*"
      authenticateOnlyIfLoggedInPattern: ".*"
      uriFilterPattern: ".*/user/.*,.*/site/(?!(index|list|elasticsearch|getImages|getPoiImages|ajaxUpdate)).*,.*/project/(?!(index|search|citizenScience|listRecordImages|projectSummaryReportCallback)).*,.*/activity/(?!index).*,.*/output/(?!index).*,.*/image/(?!index).*,.*/admin/.*,i.*/proxy/speciesListPost,.*/proxy/documentUpdate,.*/proxy/deleteDocument,.*/home/advanced,.*/organisation/(?!index).*,.*/organisation/(?!list).*,.*/bioActivity/create/.*,.*/bioActivity/edit/.*,.*/bioActivity/list,/sight/.*"
      readOnlyOfficerRole: "ROLE_FC_READ_ONLY"
      alaAdminRole : "ROLE_ADMIN"
      officerRole : "ROLE_FC_OFFICER"
      adminRole : "ROLE_FC_ADMIN"
      casServerName: "https://auth.ala.org.au"
      casServerLoginUrl: "https://auth.ala.org.au/cas/login"
      casServerUrlPrefix: "https://auth.ala.org.au/cas"
      logoutUrl: "https://auth.ala.org.au/cas/logout"

#info:
#    app:
#        name: '@info.app.name@'
#        version: '@info.app.version@'
#        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false



# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

webservice:
    connectTimeout: 6000000
    readTimeout: 6000000


collectory:
  service:
    url: "https://collections.ala.org.au"

acsaUrl: 'http://csna.gaiaresources.com.au/wordpress/'
biocache:
  baseURL: "https://biocache.ala.org.au"

# Specific configurations used by Biocollect
facets:
  flimit: 15

lists:
  commonFields: ['rawScientificName', 'matchedName', 'commonName']

speciesConfiguration:
  default: [
            "type": "ALL_SPECIES",
            "speciesDisplayFormat": "SCIENTIFICNAME(COMMONNAME)"
           ]


spatial:
   layersUrl: "${spatial.baseURL}/layers-service"
   geoserverUrl: "${spatial.baseURL}/geoserver"
   wms:
     url: "${spatial.baseURL}/geoserver/ALA/wms?"
     cache:
         url: "${spatial.baseURL}/geoserver/gwc/service/wms?"


upload:
   images:
      url : "${grails.serverURL}/image?id="
      path: "/data/${appName}/images/"
   file:
      url : "${grails.serverURL}/file?id="
   path: "/data/${appName}/"
   extensions:
      blacklist : ['exe','js','php','asp','aspx','com','bat']

ecodata:
  service:
    url: "${ecodata.baseURL}/ws"

merit:
  baseURL: "https://fieldcapture-test.ala.org.au"
  project:
    url:  "${merit.baseURL}/project/index"

headerAndFooter:
  baseURL: "https://www.ala.org.au/commonui-bs2-v2/commonui-bs2"



google:
  maps:
    base: 'https://maps.googleapis.com/maps/api/js?key='
    apiKey: 'AIzaSyA0HqqmZZT8n7bSeQ5rMZdhaCGTj4Kf_VA'
    url:  "${google.maps.base}${google.maps.apiKey ?: 'You.Need.To.Add.A.Config.Property.Named.google.maps.apiKey'}"
    geocode:
      url: "https://maps.googleapis.com/maps/api/geocode/json?"
pdfgen:
  baseURL: "http://pdfgen.ala.org.au/"

markdown:
  hardwraps: true

# Sightings
coordinates:
  sources: ["Google maps", "Google earth", "GPS device", "camera/phone", "physical maps", "other"]
sighting:
  fields:
    excludes: ['errors','timeZoneOffset','eventDateNoTime','eventDateTime','class','log','constraints','$constraints']

  licenses: ['Creative Commons Attribution','Creative Commons Attribution-Noncommercial','Creative Commons Attribution-Share Alike','Creative Commons Attribution-Noncommercial-Share Alike']

sortFields: ['scientificName','commonName','eventDate','dateCreated','lastUpdated','locality','multimedia']
accuracyValues: [0,10,50,100,500,1000,5000,10000]
flag:
  issues: ['IDENTIFICATION','GEOCODING_ISSUE','TEMPORAL_ISSUE','HABITAT_ISSUE','--','INAPPROPRIATE_IMAGE']
showBiocacheLinks: false
identify:
  subgroupFacet: "names_and_lsid"
  enabled: true
projectdata:
  industries:
    enabled: false


#
#settings:
#  surveyMethods:  "fielddata.survey.methods"
#dataAccessMethods: [
#        "oasrdfs",
#        "oaordfs",
#        "lsrds",
#        "ordfsvr",
#        "oasrdes",
#        "casrdes",
#        "rdna",
#        "odidpa",
#        "na"
#]
#
#dataQualityAssuranceMethods: [
#        "dataownercurated",
#        "subjectexpertverification",
#        "crowdsourcedverification",
#        "recordannotation",
#        "systemsupported",
#        "nodqmethodsused",
#        "na"
#    ]
#
#methodType : [
#    'opportunistic',
#    'systematic'
#]
#
#datapage:
#  defaultColumns: [
#        [
#                type: "image",
#                displayName: "Image",
#                isSortable: false
#        ],
#        [
#                type: "recordNameFacet",
#                displayName: "Identification",
#                isSortable: true,
#                sort: false,
#                order: 'asc',
#                code: "recordNameFacet"
#        ],
#        [
#                type: "symbols",
#                displayName: "",
#                isSortable: false
#        ],
#        [
#                type: "details",
#                displayName: "Details",
#                isSortable: false
#        ],
#        [
#                type: "property",
#                propertyName: "lastUpdated",
#                code: "lastUpdated",
#                displayName: "Last updated",
#                dataType: 'date',
#                isSortable: true,
#                sort: true,
#                order: 'desc'
#        ],
#        [
#                type: "action",
#                displayName: "Action",
#                isSortable: false
#        ],
#        [
#                type: "checkbox",
#                displayName: "Select item",
#                isSortable: false
#        ]
#  ]
#
#
#  extraColumns:
#     [
#        [
#                type: "property",
#                propertyName: "surveyYearFacet",
#                displayName: "Survey Year"
#        ],
#        [
#                type: "property",
#                propertyName: "projectNameFacet",
#                displayName: "Project name"
#        ],
#        [
#                type: "property",
#                propertyName: "projectActivityNameFacet",
#                displayName: "Survey name"
#        ],
#        [
#                type: "property",
#                propertyName: "organisationNameFacet",
#                displayName: "Organisation name"
#        ],
#        [
#                type: "property",
#                propertyName: "surveyMonthFacet",
#                displayName: "Survey month"
#        ],
#        [
#                type: "property",
#                propertyName: "isDataManagementPolicyDocumented",
#                displayName: ""
#        ],
#        [
#                type: "property",
#                propertyName: "dataQualityAssuranceMethods",
#                displayName: ""
#        ],
#        [
#                type: "property",
#                propertyName: "nonTaxonomicAccuracy",
#                displayName: ""
#        ],
#        [
#                type: "property",
#                propertyName: "temporalAccuracy",
#                displayName: ""
#        ],
#        [
#                type: "property",
#                propertyName: "activityLastUpdatedMonthFacet",
#                displayName: ""
#        ],
#        [
#                type: "property",
#                propertyName: "activityLastUpdatedYearFacet",
#                displayName: ""
#        ],
#        [
#                type: "property",
#                propertyName: "associatedProgramFacet",
#                displayName: ""
#        ],
#        [
#                type: "property",
#                propertyName: "siteNameFacet",
#                displayName: ""
#        ],
#        [
#                type: "property",
#                propertyName: "spatialAccuracy",
#                displayName: ""
#        ],
#        [
#                type: "property",
#                propertyName: "associatedSubProgramFacet",
#                displayName: ""
#        ],
#        [
#                type: "property",
#                propertyName: "methodType",
#                displayName: ""
#        ],
#        [
#                type: "property",
#                propertyName: "activityOwnerNameFacet",
#                displayName: "Owner"
#        ]
#  ]
#
#
#activitypropertypath: [
#        surveyYearFacet: ['surveyYear'],
#        projectNameFacet: ['projectActivity', 'projectName'],
#        projectActivityNameFacet: ['projectActivity', 'name'],
#        organisationNameFacet: ['projectActivity', 'organisationName'],
#        surveyMonthFacet: ['projectActivity', 'surveyMonth'],
#        isDataManagementPolicyDocumented: ['projectActivity', 'isDataManagementPolicyDocumented'],
#        dataQualityAssuranceMethods: ['projectActivity', 'dataQualityAssuranceMethods'],
#        nonTaxonomicAccuracy: ['projectActivity', 'nonTaxonomicAccuracy'],
#        temporalAccuracy: ['projectActivity', 'temporalAccuracy'],
#        speciesIdentification: ['projectActivity', 'speciesIdentification'],
#        activityLastUpdatedMonthFacet: ['projectActivity', 'lastUpdatedMonth'],
#        activityLastUpdatedYearFacet: ['projectActivity', 'lastUpdatedYear'],
#        associatedProgramFacet: ['associatedProgram'],
#        siteNameFacet: ['sites', 'name'],
#        associatedSubProgramFacet: ['projectActivity', 'associatedSubProgram'],
#        spatialAccuracy: ['projectActivity', 'spatialAccuracy'],
#        methodType: ['projectActivity', 'methodType'],
#        activityOwnerNameFacet: ['projectActivity', 'activityOwnerName']
#]
#
#
#content:
#  defaultOverriddenLabels: [
#        [
#                id: 1,
#                showCustomText: false,
#                page: 'Project finder',
#                defaultText: 'Showing XXXX to YYYY of ZZZZ projects',
#                customText: "",
#                notes: 'This text is generated dynamically. XXXX, YYYY & ZZZZ are replaced with dynamically generated content.'
#        ],
#        [
#                id: 2,
#                showCustomText: false,
#                page: 'Project > "About" tab',
#                defaultText: 'About the project',
#                customText: '',
#                notes: "Section heading on project's about tab."
#        ],
#        [
#                id: 3,
#                showCustomText: false,
#                page: 'Project > "About" tab',
#                defaultText: 'Aim',
#                customText: '',
#                notes: "Section heading on project's about tab."
#        ],
#        [
#                id: 4,
#                showCustomText: false,
#                page: 'Project > "About" tab',
#                defaultText: 'Description',
#                customText: '',
#                notes: "Section heading on project's about tab."
#        ],
#        [
#                id: 5,
#                showCustomText: false,
#                page: 'Project > "About" tab',
#                defaultText: 'Project information',
#                customText: '',
#                notes: "Section heading on project's about tab."
#        ],
#        [
#                id: 6,
#                showCustomText: false,
#                page: 'Project > "About" tab',
#                defaultText: 'Program name',
#                customText: '',
#                notes: "Section heading on project's about tab."
#        ],
#        [
#                id: 7,
#                showCustomText: false,
#                page: 'Project > "About" tab',
#                defaultText: 'Subprogram name',
#                customText: '',
#                notes: "Section heading on project's about tab."
#        ],
#        [
#                id: 8,
#                showCustomText: false,
#                page: "Project > About tab",
#                defaultText: 'Project Area',
#                customText: '',
#                notes: 'Section heading for Map.'
#        ]
#]
#
#map:
#  baseLayers: [
#        [
#                'code': 'minimal',
#                'displayText': 'Road map',
#                'default': false
#        ],
#        [
#                'code': 'worldimagery',
#                'displayText': 'Satellite',
#                'default': true
#        ]
#  ]
