---
grails:
    profile: web
    codegen:
        defaultPackage: au.org.ala.biocollect
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
    plugin:
       springsecurity:
          cas:
            casProperties: casServerLoginUrl,serverName,centralServer,casServerName,uriFilterPattern,uriExclusionFilter,authenticateOnlyIfLoggedInFilterPattern,casServerLoginUrlPrefix,gateway,casServerUrlPrefix,contextPath,gatewayStorageClass
            casServerName: https://auth.ala.org.au
            uriExclusionFilterPattern: /vendor.*,/images.*,/css.*,/js.*,/less.*,/ajax/bulkLookupQuestions,/uploads/.*'
            authenticateOnlyIfLoggedInFilterPattern: /,/;.*,/?.*,/[A-Za-z0-9]+/?,.*/project/(index|search|getProjectList|citizenScience|listRecordImages).*,.*/site/(index|list|elasticsearch|getImages|getPoiImages).*,.*/activity/index.*,.*/output/index.*,.*/ajax/keepSessionAlive,.*/search/.*,.*/home/.*,.*/organisation/index.*,.*/organisation/list.*
            uriFilterPattern: .*/user/.*,.*/site/(?!(index|list|elasticsearch|getImages|getPoiImages|ajaxUpdate)).*,.*/project/(?!(index|search|getProjectList|citizenScience|listRecordImages)).*,.*/activity/(?!index).*,.*/output/(?!index).*,.*/image/(?!index).*,.*/admin/.*,i.*/proxy/speciesListPost,.*/proxy/documentUpdate,.*/proxy/deleteDocument,.*/home/advanced,.*/organisation/(?!index).*,.*/organisation/(?!list).*,.*/bioActivity/create/.*,.*/bioActivity/edit/.*,.*/bioActivity/list,.*/bioActivity/ajaxUpdate/.*,*/ws/bioactivity/save.*
            casServerLoginUrl: https://auth.ala.org.au/cas/login
            casServerUrlPrefix: https://auth.ala.org.au/cas
            security.cas.logoutUrl:  https://auth.ala.org.au/cas/logout

#    config:
#        locations:
#            - file:/data/biocollect/config/biocollect-config.properties

info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false



# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

webservice:
    connectTimeout: 6000000
    readTimeout: 6000000

spatial:
   layersUrl: "${spatial.baseURL}/layers-service"
   geoserverUrl: "${spatial.baseURL}/geoserver"
   wms:
     url: "${spatial.baseURL}/geoserver/ALA/wms?"
     cache:
         url: "${spatial.baseURL}/geoserver/gwc/service/wms?"


upload:
   images:
      url : "${grails.serverURL}/image?id="
   file:
      url : "${grails.serverURL}/file?id="

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: none
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: none  #${ } will be html encoded if set to default to html
                scriptlets: html
                taglib: none
                staticparts: none
endpoints:
    jmx:
        unique-names: true

---

environments:
    development:
        grails:
           config:
              locations:
                 - file:///data/biocollect/config/biocollect-config-grails3.properties
           # It is used by redirect and others
           serverURL: "${server.serverURL}"
        bugherd:
           integration : false
#       grails:
#          serverURL: http://devt.ala.org.au:8087/biocollect/
#        ecodata:
#          service:
#            url: http://devt.ala.org.au:8080/ecodata

        server:
           #host: "devt.ala.org.au"
           #contextPath: /biocollect
           port: 8087
           serverURL: http://devt.ala.org.au:8087
        security:
          cas:
             appServerName: 'http://devt.ala.org.au:8087'
    test:
        dataSource:
            dbCreate: update
            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    production:
        grails:
            serverURL: "http://www.ala.org.au/biocollect"

